service:
  name: auction-app

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  tags:
    Owner: serverless_node_aws_user
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(iam/LambdaRoles.yml):AuctionsTablePutItem}

resources:
  Resources: # CloudFormation syntax
    AuctionsTable: ${file(resources/DynamoDB.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /get-auctions

  getAuctionById:
    handler: src/handlers/getAuctionById.handler
    events:
      - http:
          method: GET
          path: /auction/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid

custom:
  AuctionsTable:
    name: !Ref AuctionsTable # CloudFormation syntax, returns Table Name
    arn: !GetAtt AuctionsTable.Arn # CloudFormation syntax, returns Table ARN
